name: myenv
channels:
  - pytorch-nightly
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.4=py39hce1f21e_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.9.24=py39h06a4308_0
  - cffi=1.15.0=py39hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39h06a4308_0
  - cryptography=36.0.0=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - geos=3.8.0=he6710b0_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.3=py39h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libidn2=2.3.2=h7f8727e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib-base=3.5.1=py39ha18d171_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - numexpr=2.8.1=py39h6abb31d_0
  - numpy=1.21.5=py39he7a7128_2
  - numpy-base=1.21.5=py39hf524024_2
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.2=py39h295c915_0
  - pcre=8.45=h295c915_0
  - pillow=9.0.1=py39h22f2fdc_0
  - pip=21.2.4=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyyaml=6.0=py39h7f8727e_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - regex=2022.3.15=py39h7f8727e_0
  - requests=2.27.1=pyhd3eb1b0_0
  - sacremoses=0.0.43=pyhd3eb1b0_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - setuptools=61.2.0=py39h06a4308_0
  - shapely=1.7.1=py39h1728cc4_0
  - sip=4.19.13=py39h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - tokenizers=0.11.4=py39h3dcd8bd_1
  - torchaudio=0.12.0.dev20220507=py39_cu113
  - torchvision=0.13.0.dev20220507=py39_cu113
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.64.0=py39h06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.9=py39h06a4308_0
  - wget=1.21.3=h0b77cf5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.2.0
    - accelerate==0.17.1
    - aiofiles==23.1.0
    - aiohttp==3.8.4
    - aiosignal==1.2.0
    - alembic==1.8.1
    - altair==4.2.2
    - anyio==3.6.2
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - attrs==22.1.0
    - autopage==0.5.1
    - bitsandbytes==0.37.2
    - cachetools==5.2.0
    - cliff==4.0.0
    - cloudpickle==2.2.1
    - cmaes==0.8.2
    - cmake==3.26.1
    - cmd2==2.4.2
    - colorlog==6.6.0
    - dataclasses-json==0.5.7
    - datasets==2.10.2.dev0
    - dill==0.3.6
    - entrypoints==0.4
    - fastapi==0.95.0
    - ffmpy==0.3.0
    - fire==0.5.0
    - fonttools==4.34.4
    - frozenlist==1.3.1
    - fsspec==2022.7.1
    - git-lfs==1.6
    - google-auth==2.10.0
    - google-auth-oauthlib==0.4.6
    - gradio==3.24.1
    - gradio-client==0.0.7
    - greenlet==1.1.2
    - grpcio==1.47.0
    - h11==0.14.0
    - httpcore==0.16.3
    - httpx==0.23.3
    - huggingface-hub==0.13.3
    - jinja2==3.1.2
    - jsonschema==4.17.3
    - kiwisolver==1.4.4
    - langchain==0.0.132
    - latex2mathml==3.75.2
    - linkify-it-py==2.0.0
    - lit==16.0.0
    - llama-index==0.5.8
    - loralib==0.1.1
    - mako==1.2.1
    - markdown==3.4.1
    - markdown-it-py==2.2.0
    - markdown2==2.4.8
    - markupsafe==2.1.1
    - marshmallow==3.19.0
    - marshmallow-enum==1.5.1
    - matplotlib==3.5.2
    - mdit-py-plugins==0.3.3
    - mdtex2html==1.2.0
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.2
    - multiprocess==0.70.14
    - mypy-extensions==1.0.0
    - networkx==3.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.0
    - openai==0.27.4
    - optuna==2.10.1
    - orjson==3.8.9
    - patsy==0.5.2
    - pbr==5.10.0
    - peft==0.3.0.dev0
    - portalocker==2.7.0
    - prettytable==3.3.0
    - protobuf==3.19.4
    - psutil==5.9.4
    - pyarrow==11.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.10.7
    - pydeprecate==0.3.2
    - pydub==0.25.1
    - pygments==2.14.0
    - pyperclip==1.8.2
    - pyrsistent==0.19.3
    - python-multipart==0.0.6
    - pytorch-forecasting==0.10.2
    - pytorch-lightning==1.7.2
    - rdkit==2022.3.5
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rfc3986==1.5.0
    - rsa==4.9
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - semantic-version==2.10.0
    - sentencepiece==0.1.97
    - sniffio==1.3.0
    - sqlalchemy==1.4.40
    - starlette==0.26.1
    - statsmodels==0.13.2
    - stevedore==4.0.0
    - sympy==1.11.1
    - tenacity==8.2.2
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.3.0
    - threadpoolctl==3.1.0
    - tiktoken==0.3.3
    - toolz==0.12.0
    - torch==2.0.0
    - torchdata==0.6.0
    - torchmetrics==0.9.3
    - torchtext==0.15.1
    - transformers==4.28.0.dev0
    - triton==2.0.0
    - typing-extensions==4.5.0
    - typing-inspect==0.8.0
    - uc-micro-py==1.0.1
    - uvicorn==0.21.1
    - wcwidth==0.2.5
    - websockets==11.0
    - werkzeug==2.2.2
    - xxhash==3.2.0
    - yarl==1.8.1
    - zstandard==0.20.0
prefix: /home/wwang6/.conda/envs/myenv
